### ISSUE TITLE
IFTTT not the same

### ISSUE THREAD

**Issue by fabiopedrosa** [Lallassu/googlehome#1]
I'm only seeing this in IFTTT, not nearly the same as you show in the screenshot.

![image](https://user-images.githubusercontent.com/88341/32891097-500a6a22-cac9-11e7-92e2-983d0a21e1c1.png)

![image](https://user-images.githubusercontent.com/88341/32891153-77a7197c-cac9-11e7-8c3c-01fccf5f8b99.png)

Any idea why?

**Comment by Lallassu** [comment]
Oh, I forgot to mention that you need to create the applet using the maker platform. It's free to use, just activate it: https://platform.ifttt.com/maker

The  you create a private applet as per my settings in the screenshot. I hope this solves it!

**Comment by fabiopedrosa** [comment]
That was it! Thanks

A qui, 16/11/2017, 12:49, Magnus <notifications@github.com> escreveu:
